import DiffableDataSources

typealias NSDiffableDataSourceSnapshot = DiffableDataSourceSnapshot
typealias UICollectionViewDiffableDataSource = CollectionViewDiffableDataSource
typealias UITableViewDiffableDataSource = TableViewDiffableDataSource
